<a href="https://colab.research.google.com/github/Shri0807/Machine-Learning-Projects/blob/Regression/Car_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset


In [ ]:
dataset = pd.read_csv('car data.csv')
X = dataset.iloc[:, [3, 4, 6, 7, 8]].values
y = dataset.iloc[:, 2].values

In [ ]:
print(X)

[[5.59 27000 'Dealer' 'Manual' 0]
 [9.54 43000 'Dealer' 'Manual' 0]
 [9.85 6900 'Dealer' 'Manual' 0]
 ...
 [11.0 87934 'Dealer' 'Manual' 0]
 [12.5 9000 'Dealer' 'Manual' 0]
 [5.9 5464 'Dealer' 'Manual' 0]]


In [ ]:
print(y)

[ 3.35  4.75  7.25  2.85  4.6   9.25  6.75  6.5   8.75  7.45  2.85  6.85
  7.5   6.1   2.25  7.75  7.25  7.75  3.25  2.65  2.85  4.9   4.4   2.5
  2.9   3.    4.15  6.    1.95  7.45  3.1   2.35  4.95  6.    5.5   2.95
  4.65  0.35  3.    2.25  5.85  2.55  1.95  5.5   1.25  7.5   2.65  1.05
  5.8   7.75 14.9  23.   18.   16.    2.75  3.6   4.5   4.75  4.1  19.99
  6.95  4.5  18.75 23.5  33.    4.75 19.75  9.25  4.35 14.25  3.95  4.5
  7.45  2.65  4.9   3.95  5.5   1.5   5.25 14.5  14.73  4.75 23.   12.5
  3.49  2.5  35.    5.9   3.45  4.75  3.8  11.25  3.51 23.    4.    5.85
 20.75 17.    7.05  9.65  1.75  1.7   1.65  1.45  1.35  1.35  1.35  1.25
  1.2   1.2   1.2   1.15  1.15  1.15  1.15  1.11  1.1   1.1   1.1   1.05
  1.05  1.05  1.05  1.    0.95  0.9   0.9   0.75  0.8   0.78  0.75  0.75
  0.75  0.72  0.65  0.65  0.65  0.65  0.6   0.6   0.6   0.6   0.6   0.6
  0.6   0.6   0.55  0.55  0.52  0.51  0.5   0.5   0.5   0.5   0.5   0.48
  0.48  0.48  0.48  0.45  0.45  0.45  0.45  0.45  0.45 

# Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2, 3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 5.59 27000 0]
 [1.0 0.0 0.0 ... 9.54 43000 0]
 [1.0 0.0 0.0 ... 9.85 6900 0]
 ...
 [1.0 0.0 0.0 ... 11.0 87934 0]
 [1.0 0.0 0.0 ... 12.5 9000 0]
 [1.0 0.0 0.0 ... 5.9 5464 0]]


# Splitting the dataset into the Training set and Test set


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)


[[0.0 1.0 0.0 ... 1.78 4000 0]
 [1.0 0.0 0.0 ... 14.89 23000 0]
 [1.0 0.0 0.0 ... 9.4 71000 0]
 ...
 [1.0 0.0 0.0 ... 18.61 56001 0]
 [1.0 0.0 0.0 ... 9.4 15141 0]
 [0.0 1.0 0.0 ... 2.28 127000 0]]


In [ ]:
print(X_test)

[[1.0 0.0 1.0 0.0 8.5 15059 0]
 [1.0 0.0 0.0 1.0 4.6 30000 0]
 [0.0 1.0 0.0 1.0 0.826 6000 0]
 [1.0 0.0 0.0 1.0 4.43 15000 0]
 [0.0 1.0 0.0 1.0 1.5 15000 0]
 [1.0 0.0 0.0 1.0 7.13 12479 0]
 [0.0 1.0 0.0 1.0 0.95 3500 0]
 [1.0 0.0 0.0 1.0 5.71 43000 0]
 [1.0 0.0 0.0 1.0 13.6 34000 0]
 [0.0 1.0 0.0 1.0 0.84 23000 0]
 [1.0 0.0 0.0 1.0 9.4 19434 0]
 [1.0 0.0 0.0 1.0 6.05 47000 0]
 [1.0 0.0 0.0 1.0 5.9 5464 0]
 [1.0 0.0 0.0 1.0 6.8 39485 1]
 [0.0 1.0 0.0 1.0 0.75 49000 1]
 [0.0 1.0 1.0 0.0 0.57 24000 0]
 [1.0 0.0 0.0 1.0 10.38 51000 0]
 [1.0 0.0 0.0 1.0 9.4 45000 0]
 [1.0 0.0 1.0 0.0 9.4 36198 0]
 [1.0 0.0 0.0 1.0 10.38 45000 0]
 [0.0 1.0 0.0 1.0 6.49 16200 0]
 [1.0 0.0 0.0 1.0 9.9 38000 0]
 [1.0 0.0 1.0 0.0 22.83 80000 0]
 [1.0 0.0 1.0 0.0 9.94 15000 0]
 [0.0 1.0 1.0 0.0 23.73 142000 3]
 [1.0 0.0 0.0 1.0 5.09 35500 0]
 [1.0 0.0 0.0 1.0 11.0 87934 0]
 [0.0 1.0 0.0 1.0 0.95 16600 0]
 [0.0 1.0 0.0 1.0 0.51 60000 0]
 [0.0 1.0 0.0 1.0 1.05 30000 0]
 [0.0 1.0 0.0 1.0 0.58 30000 0]
 [0.0 1.0 0.0 

# Evaluating Model

In [ ]:
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

In [ ]:
cv=5 # CV value
r_2 = [] # List for r 2 score
CV = [] # list for CV scores mean
def model(algorithm, X_train, y_train, X_test, y_test): 
  algorithm.fit(X_train, y_train)
  predicts=algorithm.predict(X_test)
  prediction=pd.DataFrame(predicts)
  R_2=r2_score(y_test,prediction)
  cross_val=cross_val_score(algorithm, X_train, y_train, cv=cv)
  r_2.append(R_2)
  CV.append(cross_val.mean())

  #Printing results
  print(algorithm,"\n") 
  print("r_2 score :",R_2,"\n")
  print("CV scores:",cross_val,"\n")
  print("CV scores mean:",cross_val.mean())



# Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model(lr, X_train, y_train, X_test, y_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False) 

r_2 score : -55853383.05414573 

CV scores: [0.78801622 0.86008917 0.75811856 0.72118347 0.57618044] 

CV scores mean: 0.740717570850423


# Decision Tree Regression

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state = 0)
model(dtr, X_train, y_train, X_test, y_test)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best') 

r_2 score : -25.22630828270423 

CV scores: [0.71987812 0.80134063 0.73724592 0.8224063  0.6977806 ] 

CV scores mean: 0.7557303111638612


# Random Forest Regression 

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators = 10, random_state = 0)
model(rfr, X_train, y_train, X_test, y_test)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False) 

r_2 score : -17.38765777185127 

CV scores: [0.84991939 0.90872404 0.8330694  0.83161336 0.74038601] 

CV scores mean: 0.8327424366258274


# Support Vector Regression

In [ ]:
y = y.reshape(len(y),1)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
#y_train = sc_y.fit_transform(y_train)


In [ ]:
from sklearn.svm import SVR
svr = SVR(kernel = 'rbf')
model(svr, X_train, y_train, X_test, y_test)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False) 

r_2 score : -0.015439809708707841 

CV scores: [0.75383893 0.46496808 0.64663418 0.73448926 0.20729709] 

CV scores mean: 0.5614455084594356
