<a href="https://colab.research.google.com/github/Shri0807/Machine-Learning-Projects/blob/Regression/Real_estate_valuation_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing Dataset

In [4]:
dataset = pd.read_csv('Real estate valuation data set.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[2012.917     32.        84.87882   10.        24.98298  121.54024]
 [2012.917     19.5      306.5947     9.        24.98034  121.53951]
 [2013.583     13.3      561.9845     5.        24.98746  121.54391]
 ...
 [2013.25      18.8      390.9696     7.        24.97923  121.53986]
 [2013.         8.1      104.8101     5.        24.96674  121.54067]
 [2013.5        6.5       90.45606    9.        24.97433  121.5431 ]]


In [6]:
print(y)

[ 37.9  42.2  47.3  54.8  43.1  32.1  40.3  46.7  18.8  22.1  41.4  58.1
  39.3  23.8  34.3  50.5  70.1  37.4  42.3  47.7  29.3  51.6  24.6  47.9
  38.8  27.   56.2  33.6  47.   57.1  22.1  25.   34.2  49.3  55.1  27.3
  22.9  25.3  47.7  46.2  15.9  18.2  34.7  34.1  53.9  38.3  42.   61.5
  13.4  13.2  44.2  20.7  27.   38.9  51.7  13.7  41.9  53.5  22.6  42.4
  21.3  63.2  27.7  55.   25.3  44.3  50.7  56.8  36.2  42.   59.   40.8
  36.3  20.   54.4  29.5  36.8  25.6  29.8  26.5  40.3  36.8  48.1  17.7
  43.7  50.8  27.   18.3  48.   25.3  45.4  43.2  21.8  16.1  41.   51.8
  59.5  34.6  51.   62.2  38.2  32.9  54.4  45.7  30.5  71.   47.1  26.6
  34.1  28.4  51.6  39.4  23.1   7.6  53.3  46.4  12.2  13.   30.6  59.6
  31.3  48.   32.5  45.5  57.4  48.6  62.9  55.   60.7  41.   37.5  30.7
  37.5  39.5  42.2  20.8  46.8  47.4  43.5  42.5  51.4  28.9  37.5  40.1
  28.4  45.5  52.2  43.2  45.1  39.7  48.5  44.7  28.9  40.9  20.7  15.6
  18.3  35.6  39.4  37.4  57.8  39.6  11.6  55.5  5

# Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

# Evaluate Model

In [8]:
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

In [9]:
cv=5 # CV value
r_2 = [] # List for r 2 score
CV = [] # list for CV scores mean
def model(algorithm, X_train, y_train, X_test, y_test): 
  algorithm.fit(X_train, y_train)
  predicts=algorithm.predict(X_test)
  prediction=pd.DataFrame(predicts)
  R_2=r2_score(y_test,prediction)
  cross_val=cross_val_score(algorithm, X_train, y_train, cv=cv)
  r_2.append(R_2)
  CV.append(cross_val.mean())

  #Printing results
  print(algorithm,"\n") 
  print("r_2 score :",R_2,"\n")
  print("CV scores:",cross_val,"\n")
  print("CV scores mean:",cross_val.mean())

# Linear Regression

In [33]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression(normalize=False)
model(lr, X_train, y_train, X_test, y_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False) 

r_2 score : 0.7034608498765533 

CV scores: [0.364215   0.66690026 0.47672117 0.62559996 0.47745142] 

CV scores mean: 0.522177561423103


# Support Vector Regression

In [31]:
from sklearn.svm import SVR
svr = SVR(kernel = 'rbf', epsilon=0.1)
model(svr, X_train, y_train, X_test, y_test)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False) 

r_2 score : 0.6191321616989907 

CV scores: [0.23812483 0.55039848 0.46070087 0.58138473 0.4896844 ] 

CV scores mean: 0.4640586626374323


In [12]:
from sklearn.svm import SVR
svr = SVR(kernel = 'poly')
model(svr, X_train, y_train, X_test, y_test)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False) 

r_2 score : 0.6191307977007338 

CV scores: [0.23507578 0.53035936 0.45004752 0.5585528  0.46543924] 

CV scores mean: 0.44789493984296624


In [13]:
from sklearn.svm import SVR
svr = SVR(kernel = 'sigmoid')
model(svr, X_train, y_train, X_test, y_test)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='sigmoid', max_iter=-1, shrinking=True, tol=0.001, verbose=False) 

r_2 score : 0.45369881748858043 

CV scores: [0.16943338 0.41778314 0.33936701 0.34748868 0.36301588] 

CV scores mean: 0.32741761592592517


# Decision Tree Regression

In [14]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state = 0)
model(dtr, X_train, y_train, X_test, y_test)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best') 

r_2 score : 0.5271743227100754 

CV scores: [ 0.45736155  0.60120513 -0.01716406  0.79541075 -0.00918352] 

CV scores mean: 0.3655259705002966


# Random Forest Regression

In [37]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators = 400, random_state = 0, max_depth=70, min_samples_leaf=4, min_samples_split=10)
model(rfr, X_train, y_train, X_test, y_test)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=70, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=4,
                      min_samples_split=10, min_weight_fraction_leaf=0.0,
                      n_estimators=400, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False) 

r_2 score : 0.7371309859304636 

CV scores: [0.55259498 0.84651845 0.67494188 0.78688311 0.56324005] 

CV scores mean: 0.6848356952422263
